global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    monitor: prometheus-swarm
rule_files:
  - alert.rules_nodes
  - alert.rules_tasks
  - alert.rules_service-groups
scrape_configs:
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "kafka"
    static_configs:
      - targets:
        - jmx-exporter-broker:5556
        - jmx-exporter-controller:5556
        - kafka_exporter:9308
