{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and consumer lag overview",
 "tags": [ "Kafka" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kafka_job_name",
    "label": "kafka_job_name",
    "query": {
     "query": "kafka_server_brokertopicmetrics_bytesout_total"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "kafka_server_brokertopicmetrics_bytesout_total{job=\"$kafka_job_name\"}"
    }
   },
   {
    "name": "topic",
    "label": "Topics",
    "query": {
     "query": "label_values(kafka_log_log_size, topic)"
    }
   },
   {
    "name": "cg",
    "label": "Consumer",
    "query": {
     "query": "label_values(kafka_consumergroup_lag, consumergroup)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Brokers Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activebrokercount{job=\"$kafka_job_name\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Consumer Threads Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_members{job=\"$kafka_job_name\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Partitions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{job=\"$kafka_job_name\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Controller Node",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(kafka_controller_kafkacontroller_activecontrollercount{job=\"$kafka_job_name\"}, \"instance\", \"$1\", \"instance\", \"(.*):(.*)\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumer Groups by State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroups{job=\"$kafka_job_name\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupsstable{job=\"$kafka_job_name\"})",
     "legendFormat": "Stable"
    },
    {
     "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupsempty{job=\"$kafka_job_name\"})",
     "legendFormat": "Empty"
    },
    {
     "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupsdead{job=\"$kafka_job_name\"})",
     "legendFormat": "Dead"
    },
    {
     "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupspreparingrebalance{job=\"$kafka_job_name\"})",
     "legendFormat": "Preparing Rebalance"
    },
    {
     "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupscompletingrebalance{job=\"$kafka_job_name\"})",
     "legendFormat": "Completing Rebalance"
    }
   ]
  },
  {
   "title": "Offline partitions %",
   "type": "timeseries",
   "description": "% of partitions are not available. Zero means stable",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=\"$kafka_job_name\"}) / sum(kafka_topic_partitions{job=\"$kafka_job_name\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ISR expands by instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(rate(kafka_server_replicamanager_isrexpands_total[1m]), \"instance\", \"$1\", \"instance\", \"(.*):(.*)\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Disk Usages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Kafka log size by topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_log_log_size{job=\"$kafka_job_name\", topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka log size by broker (disk space utilization)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_log_log_size{job=\"$kafka_job_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Topics with Total Messages ",
   "type": "table",
   "description": "Total messages pushed in the topics in the selected duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance, pod) (increase(kafka_server_brokertopicmetrics_messagesin_total{job=\"$kafka_job_name\", topic=~\"$topic\"}[$__range]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Top 10 Topics with Incoming Data",
   "type": "table",
   "description": "Total data pushed in the topics in the selected duration",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (increase(kafka_server_brokertopicmetrics_bytesin_total{job=\"$kafka_job_name\", cluster=\"$cluster_name\", topic=~\"$topic\"}[$__range]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Topic-Consumers Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Consumers Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kafka_consumergroup_current_offset_sum{cluster=\"$cluster_name\", topic=~\"$topic\", consumergroup=~\"$cg\"}[$__rate_interval])",
     "legendFormat": "{{consumergroup}} @ {{topic}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_log_log_logendoffset{topic=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer lag by group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(consumergroup, topic) (kafka_consumergroup_lag{job=\"$kafka_job_name\", topic=~\"$topic\", consumergroup=~\"$cg\"})",
     "legendFormat": "{{consumergroup}}@{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Members",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_consumergroup_members{cluster=\"$cluster_name\", consumergroup=~\"$cg\"}",
     "legendFormat": "{{consumergroup}} "
    }
   ]
  },
  {
   "title": "Consumer Lag Delta [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(consumergroup, topic) (delta(kafka_consumergroup_lag{job=\"$kafka_job_name\", topic=~\"$topic\", consumergroup=~\"$cg\"}[1m]))",
     "legendFormat": "{{consumergroup}}@{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Lag Avg Delta [1m]",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(consumergroup, topic) (delta(kafka_consumergroup_lag{job=\"$kafka_job_name\", topic=~\"$topic\", consumergroup=~\"$cg\"}[1m]))",
     "legendFormat": "{{consumergroup}}@{{topic}}"
    }
   ]
  },
  {
   "title": "Topics Bytes I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes In Per Topic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"$kafka_job_name\", topic=~\"$topic\"}[5m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Bytes Out Per Topic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum without(instance, pod) (rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"$kafka_job_name\", topic=~\"$topic\"}[5m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$kafka_job_name\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors / Limit %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$kafka_job_name\", cluster=\"$cluster_name\", instance!=\"10.10.18.89:9308\"} / process_max_fds{job=\"$kafka_job_name\", cluster=\"$cluster_name\", instance!=\"10.10.18.89:9308\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"$kafka_job_name\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"$kafka_job_name\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Cleaner Last Run",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_log_logcleanermanager_time_since_last_run_ms{cluster=\"$cluster_name\"}",
     "legendFormat": "{{cluster}}@{{instance}}"
    }
   ]
  }
 ]
}